// "use client";
// import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/authLoginLogout";
const kanitSans = Kanit({
   variable: "--font-kanit-sans",
   subsets: ["thai"],
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// const geistMono = Kanit({
//    variable: "--font-geist-mono",
//    subsets: ["thai"],
//    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

// export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
// };

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <AuthProvider>
            <body className={`${kanitSans.variable} `}>{children}</body>
         </AuthProvider>
      </html>
   );
}
